Add telemetry message v3
smartcontractkit/chainlink-solana pull request #23
Opened 2021-12-13 04:27 UTC by pedrovsg

2021-12-13 16:28 UTC, topliceanu requested changes

2021-12-13 16:28 UTC, topliceanu commented on cmd/monitoring/main.go
> +	telemetryProducer, err := monitoring.NewProducer(ctx, cfg.Kafka, cfg.Kafka.TelemetryTopic)
I find this namic confusing: both `tel` and `telemetry`. They are also not telemetry, telemetry is done in offchain reporting in the `chainlink` repo. How about using `configSetSchema` and `configSetSimplifiedSchema`?

2021-12-13 16:28 UTC, topliceanu commented on pkg/monitoring/config.go
>  	}
Please rename this topic as well.

2021-12-13 16:28 UTC, topliceanu commented on pkg/monitoring/feed_monitor.go
> +func (f *feedMonitor) processTelemetry(envelope StateEnvelope) error {
As I understand it, this is not telemetry, in the chainlink-ocr2 sense, no?! Telemetry goes into the implementation of `types.MonitoringEndpoint`. Please rename this helper

2021-12-13 16:28 UTC, topliceanu commented on pkg/monitoring/mapping.go
> +	s, err := convertToJson(int32ArrToInt64Arr(offchainConfig.S))
`convertToJson` is a alias of `encoding/json#Marshal`! Just use `Marshal`

2021-12-13 16:28 UTC, topliceanu commented on pkg/monitoring/schemas.go
> +}
The way we encode schemas has changed in the main branch.
I'll push and update on the main branch!

2021-12-14 16:39 UTC, pedrovsg commented on pkg/monitoring/mapping.go
> +		"feed_contract_status": feedConfig.ContractStatus,
this is wrong, should be state_account

2021-12-15 03:06 UTC, closed without merging