update libocr + add new MaxReportLength method
smartcontractkit/chainlink-solana pull request #308
Opened 2022-04-18 21:33 UTC by aalu1418

2022-04-19 07:00 UTC, kaleofduty approved these changes, later dismissed

2022-04-20 13:37 UTC, topliceanu submitted a review, later dismissed

2022-04-20 17:18 UTC, kaleofduty requested changes, later dismissed

2022-04-20 17:18 UTC, kaleofduty commented on pkg/solana/report.go
> +		return nil, errors.Wrap(err, "error in DeserializeSigned(juelsPerFeeCoin)")
wrong function

2022-04-20 19:16 UTC, aalu1418 commented
Note: e2e tests won't pass right now because of a new method introduced in the libocr report codec

so the develop branches across solana/terra/core don't have the required interface

2022-04-20 20:02 UTC, jmank88 approved these changes

2022-04-20 20:04 UTC, merged