Include SetComputeUnitPrice in reimbursement calculation
smartcontractkit/chainlink-solana pull request #405
Opened 2022-10-06 17:57 UTC by archseer

2022-11-09 14:41 UTC, aalu1418 requested changes
looking good! just one fix that has to be addressed, the other comment would be nice but I would at least like confirmation that this doesn't break things if the program is upgraded before the nodes

2022-11-09 14:41 UTC, aalu1418 commented on contracts/programs/ocr2/src/lib.rs
> +    const MICRO: u64 = 10u64.pow(3);
```suggestion
    const MICRO: u64 = 10u64.pow(6);
```

2022-11-09 14:41 UTC, aalu1418 commented on contracts/tests/ocr2.spec.ts
> +          { pubkey: SYSVAR_INSTRUCTIONS_PUBKEY, isWritable: false, isSigner: false },
nit: is there a test case where `SYSVAR_INSTRUCTIONS_PUBKEY` isn't passed to the contract?

thinking about the case where the contract is upgraded before the node is upgraded (or vice versa)

2022-11-09 14:41 UTC, aalu1418 commented on contracts/tests/ocr2.spec.ts
> +    let computeUnitCostLamports = execUnits * computePrice / Math.pow(10, 3);
```suggestion
    let computeUnitCostLamports = execUnits * computePrice / Math.pow(10, 6);
```

2022-11-10 09:04 UTC, archseer commented
> but I would at least like confirmation that this doesn't break things if the program is upgraded before the nodes

No tests since I'd like to remove this codepath soon but I reverted https://github.com/smartcontractkit/chainlink-solana/pull/405/commits/c81b45835739bb157e401c1d5f4f5902c2f215ba and ran the tests to ensure they still pass

2022-11-10 15:49 UTC, aalu1418 approved these changes
LGTM!

this can be merged as long as we are sure that the program change is compatible in both ways:
old CL node <=> new programs
new CL node <=> old programs

2022-11-11 01:34 UTC, archseer commented
CL nodes shouldn't upgrade until the program is first upgraded.

2022-11-22 16:23 UTC, merged