Chore/qa 1202 sonarqube integration
smartcontractkit/chainlink-solana pull request #506
Opened 2023-05-11 13:13 UTC by davidcauchi

2023-06-14 19:13 UTC, aalu1418 reviewed
overall looks good! just the linter failing on the workflow files?

2023-06-23 12:55 UTC, jmank88 submitted a review, later dismissed

2023-06-27 18:16 UTC, aalu1418 submitted a review, later dismissed

2023-07-04 12:56 UTC, krebernisak commented on .github/workflows/unit-testing-and-static-analysis.yml
> +  tools:
CI custom setup is deprecated.

We should use Nix to declare environments where we execute our code.

2023-07-04 12:56 UTC, krebernisak commented on .github/workflows/unit-testing-and-static-analysis.yml
> +        run: go test ./pkg/... -v -race -count=10 -timeout=15m -coverpkg=./... -coverprofile=race_coverage.txt
Declaring custom CI steps inside a workflow is deprecated.

Please move these actions to Makefile and trigger them with make - we want all relevant project actions in a single place.

2023-07-04 12:56 UTC, krebernisak commented on .github/workflows/unit-testing-and-static-analysis.yml
> +  tools:
To indicate this please wrap all env setup code in comments `##TODO: replace with Nix` - we're going to work on this in Q3. cc @archseer @augustbleeds

2023-07-04 12:56 UTC, krebernisak commented on .github/workflows/unit-testing-and-static-analysis.yml
> +    name: SonarQube Scan
Is there a way to centralize this workflow so each project doesn't need to define it? (e.g., pull a list of projects and scan them in a central place).

How do we plan to verify external projects/integrations?

2023-07-04 12:56 UTC, krebernisak commented on sonar-project.properties
> +# Full exclusions from the static analysis
What is the general rule to follow in regards inclusions/exclusions?

e.g., Do we analyse our Gauntlet code? Which components we do vs. don't, and why?

2023-07-04 12:56 UTC, krebernisak commented on .github/workflows/unit-testing-and-static-analysis.yml
> +  relay_run_unit_tests:
Naming is off as this will also build and test monitoring code in /pkg/monitoring, which represents a separate service.

2023-07-04 12:56 UTC, krebernisak commented on .github/workflows/unit-testing-and-static-analysis.yml
> +  relay_run_unit_tests:
Can we somehow externalize this job in a separate workflow and depend on it here?

We have more components than just Go relayer to test and scan, so there might be a few of these jobs.

2023-07-04 13:03 UTC, krebernisak commented on .github/workflows/unit-testing-and-static-analysis.yml
> +  relay_run_unit_tests:
Looking at this looks like we can: https://github.com/smartcontractkit/chainlink-cosmos/pull/339/files

Please restructure CI workflows for all three projects so they are structured and named consistently.

2023-09-06 05:35 UTC, smickovskid commented on sonar-project.properties
> +# Full exclusions from the static analysis
We initially start by setting it up with our go tests to get it up and running, idea is to add additional checks as we decide we need them which should be plug and play

2023-09-06 07:35 UTC, cfal submitted a review, later dismissed

2023-09-06 13:24 UTC, chudilka1 requested changes

2023-09-06 13:24 UTC, chudilka1 commented on sonar-project.properties
> +# Full exclusions from the static analysis
Exclusions let you ignore everything you do not want to get static analysis results for.

2023-09-06 13:24 UTC, chudilka1 commented on .github/workflows/sonar-scan.yml
> +        uses: actions/download-artifact@9782bd6a9848b53b110e712e20e42d89988822b7 # v3.0.1
When Sonar is triggered in a separate workflow, the traditional download artifact action won't upload any (see the results [here](https://github.com/smartcontractkit/chainlink-solana/actions/runs/6083905420/job/16505025707?pr=506#step:4:7)). Please, use the same approach as in starknet repo for downloading different artifacts from independent flows.
```
      - name: Download Golangci Relayer report
        uses: dawidd6/action-download-artifact@v2.27.0
        with:
          workflow: golangci-lint.yml
          workflow_conclusion: ""
          name: golangci-lint-relayer-report
          if_no_artifact_found: warn
```

2023-09-11 10:00 UTC, chudilka1 requested changes

2023-09-11 10:00 UTC, chudilka1 commented on .github/workflows/sonar-scan.yml
> +name: Unit testing and static analysis
There are no unit testing steps in the workflow, please rename it by removing `unit testing` part

2023-09-11 10:00 UTC, chudilka1 commented on .github/workflows/relay.yml
> +            ./coverage.txt
Do you produce `output`? If not remove.

2023-09-11 10:00 UTC, chudilka1 commented on .github/workflows/relay.yml
> +        run: go test ./pkg/... -v -race -count=10 -timeout=15m -covermode=atomic -coverpkg=./... -coverprofile=coverage.txt
name it `race_coverage` to differentiate between different results.

2023-09-11 10:00 UTC, chudilka1 commented on .github/workflows/golangci-lint.yml
>            args: --enable=gofmt --tests=false --exclude-use-default --timeout=5m0s
This command won't produce a report, add `--out-format checkstyle:golangci-lint-report.xml` After done, verify in the corresponding workflow, that the artifact is uploading and in sonar-scan.yml, you get it (take a look [here](https://github.com/smartcontractkit/chainlink-solana/actions/runs/6143326053/job/16666756273#step:7:3), the path for linter should not be empty)

2023-09-13 05:18 UTC, smickovskid approved these changes

2023-09-13 05:21 UTC, merged